### ISSUE TITLE
Deletion Bug

### ISSUE THREAD

**Issue by exactlyprecise** [CS2103-AY1819S2-W16-1/main#224]
Even though delete normally works in removing a person from the meetings (the names seem to be gone)
To cause a delete bug:
1. Meet 1 2 3
2. switch
3. edit 1 n/Scrub
4. delete 1
5. switch
The person does not get deleted this time.
Note: Might be caused by searching for the name in delete, or might be because deleting a person's name uses a reference to a person, which is gone when you create a new person due to edit command.

**Comment by yonggqiii** [comment]
Thanks! This was really valuable.
You were right in your note, editing the person did not change the state of the event containing the person before editing, thus deleting the newly edited person did not affect the events.
Further, this issue uncovered a serious bug, in that editing and deleting persons changed the state of the event as well, causing issues with the VersionedAddressBook.
All the above have been resolved. Great find!
